In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn import metrics

In [2]:
df = pd.read_csv('data.csv')

In [20]:
df.head()

,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,Sload,Dload,Spkts,...,service_ssh,service_ssl,is_sm_ips_ports_True,ct_state_ttl_1,ct_state_ttl_2,ct_state_ttl_3,ct_state_ttl_4,ct_state_ttl_5,ct_state_ttl_6,is_ftp_login_True
0,5.246383e-13,6.564195e-08,8.155515e-08,1.541591e-08,1.442134e-08,0.0,0.0,0.000249,0.000309,9.945750e-10,...,0,0,0,0,0,0,0,0,0,0
1,1.796849e-11,2.625678e-07,1.511754e-07,1.541591e-08,1.442134e-08,0.0,0.0,0.000044,0.000025,1.989150e-09,...,0,0,0,0,0,0,0,0,0,0
2,5.564647e-13,7.260397e-08,8.851717e-08,1.541591e-08,1.442134e-08,0.0,0.0,0.000260,0.000316,9.945750e-10,...,0,0,0,0,0,0,0,0,0,0
3,6.012206e-13,6.564195e-08,8.155515e-08,1.541591e-08,1.442134e-08,0.0,0.0,0.000217,0.000270,9.945750e-10,...,0,0,0,0,0,0,0,0,0,0
4,5.813291e-13,7.260397e-08,8.851717e-08,1.541591e-08,1.442134e-08,0.0,0.0,0.000248,0.000303,9.945750e-10,...,0,0,0,0,0,0,0,0,0,0

In [21]:
df.shape

(700001, 206)

In [17]:
labels = pd.read_csv('anomaly_labels.csv')
labels.Label = [-x if x == 1 else 1 for x in labels.Label ]
anomaly_labels = labels.Label

In [22]:
iso_model = IsolationForest(random_state=0).fit(df)

anomaly_preds = iso_model.predict(df)
pd.crosstab(anomaly_labels, anomaly_preds)

col_0     -1       1
Label
-1     13970    8245
 1     34393  643393

In [25]:
print(metrics.silhouette_score(df, anomaly_preds, metric='euclidean'))